#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

#test_upgrade_from.53399263e4cef2c8cafd63322ca13e6113da1ae2.name = "Upgrade from 2025.12.14~ynh1"
