#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Settings added to config panel
server_name="\"4get\"";
server_short_description="\"4get is a proxy search engine.\"";
server_long_description="null";
default_theme="\"Dark\"";
api_enabled=true;
marginalia_api_key="null";
proxlist="";

proxy_ddg=false;
proxy_yahoo=false;
proxy_yahoo_japan=false;
proxy_brave=false;
proxy_fb=false;
proxy_google=false;
proxy_google_api=false;
proxy_google_cse=false;
proxy_mullvad_google=false;
proxy_mullvad_brave=false;
proxy_startpage=false;
proxy_qwant=false;
proxy_baidu=false;
proxy_coccoc=false;
proxy_ghostery=false;
proxy_marginalia=false;
proxy_mojeek=false;
proxy_sc=false;
proxy_swisscows=false;
proxy_spotify=false;
proxy_solofield=false;
proxy_wiby=false;
proxy_curlie=false;
proxy_yt=false;
proxy_archiveorg=false;
proxy_sepiasearch=false;
proxy_odysee=false;
proxy_vimeo=false;
proxy_yep=false;
proxy_pinterest=false;
proxy_sankakucomplex=false;
proxy_flickr=false;
proxy_fivehpx=false;
proxy_vsco=false;
proxy_seznam=false;
proxy_naver=false;
proxy_greppr=false;
proxy_crowdview=false;
proxy_mwmbl=false;
proxy_ftm=false;
proxy_imgur=false;
proxy_cara=false;
proxy_yandex_w=false;
proxy_yandex_i=false;
proxy_yandex_v=false;

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

# Remove useless directory 
ynh_safe_rm $install_dir/docker

# Remove TOR links from homepage as not implemented in this package so far
ynh_replace --match="^.*onion\">Tor.*$" --replace="" --file="$install_dir/template/home.html"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_safe_rm "$install_dir/data/config.php" #remove upstream default file
ynh_config_add --template="config.php" --destination="$install_dir/data/config.php"

# Create proxies file 
touch $install_dir/data/proxies/custom_proxies.txt

# Set restrictive permissions for private resources
chown -R "$app:$app" "$install_dir/data"
chmod -R 400 $install_dir/data/*

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
